POST http://localhost:3333/users HTTP/1.1
content-type: application/json

{
  "name": "John Doe",
  "email": "johndoe@acme.com",
  "password": "34991192543"
}

###

POST http://localhost:3333/users/recovery-password HTTP/1.1
content-type: application/json

{
  "email": "johndoe@acme.com"
}

###

POST http://localhost:3333/users/reset-password HTTP/1.1
content-type: application/json

{
  "token": "4f0afebc-aad5-4fc3-822d-18cf34b8aa60",
  "newPassword": "34991192543",
  "confirmPassword": "34991192543"
}